"""creaacion de tabla de  mascotas

Revision ID: b46fcca2b3a5
Revises: d25e7dc2b77e
Create Date: 2023-08-09 15:58:17.684677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46fcca2b3a5'
down_revision = 'd25e7dc2b77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mascotas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('Perro', 'Gato', 'Cuy', name='tipomascota'), nullable=False),
    sa.Column('sexo', sa.Enum('Macho', 'Hembra', 'Helicoptero', 'Otro', name='sexomascota'), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mascotas')
    # ### end Alembic commands ###
