"""elimine columna direccions

Revision ID: d25e7dc2b77e
Revises: 3534c2c5b801
Create Date: 2023-07-29 01:19:59.217642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25e7dc2b77e'
down_revision = '3534c2c5b801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.TEXT(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
